---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.component_id}}-dev
  namespace: ${{values.gitops_namespace}}
  labels:
    # argocd/app-name: ${{values.component_id}}-dev
    wzhlab.top/app-name: ${{values.component_id}}-dev
  annotations:
    # argocd/app-name: ${{values.component_id}}-dev
    wzhlab.top/app-name: ${{values.component_id}}-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: ${{values.destination}}
    targetRevision: main
    path: ./helm/app
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.namespace}}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].image | select(startswith("image-registry.openshift-image-registry.svc:5000"))
