# postgres setting for bitnami chart and openshift deployment
postgresql:
  auth:
      username: nestjs
      password: nestjs
      database: pois
  primary:
    podSecurityContext:
      enabled: false
    persistence:
      enabled: false
    containerSecurityContext:
      enabled: false
    labels:
      app.kubernetes.io/part-of: idp-book-example
  initdb:
    scripts:
      db_init.sql: |
        -- CreateTable
        CREATE TABLE "Poi" (
        "id" BIGSERIAL NOT NULL,
        "name" TEXT NOT NULL,
        "description" TEXT,
        "latitude" DOUBLE PRECISION NOT NULL,
        "longitude" DOUBLE PRECISION NOT NULL,
        "type" TEXT NOT NULL,
        CONSTRAINT "Poi_pkey" PRIMARY KEY ("id")
        );