apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: wzh-quarkus-with-angular
  title: WZH Quarkus Service with hosted Angular Frontend
  description: WZH Creates a Quarkus service hosting an Angular frontend
  tags:
    - java
    - quarkus
    - quinoa
    - angular
    - book
spec:
  owner: rhdh-idp-book-authors
  type: service

  parameters:
    - title: Provide information about the GitHub location
      required:
        - githubOrg
      properties:
        git_host:
          title: Git host
          type: string
          default: github.com
        githubOrg:
          title: GitHub Organization
          type: string
          default: nepdemo
        repoName:
          title: Repository Name
          type: string
          default: rhdh-book1-templates
        # git_token:
        #   title: GitHub access token
        #   type: string
        #   description: GitHub access token
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
          default: WZH Quarkus Service with hosted Angular Frontend
    - title: Provide information about the new component
      required:
        - cluster_id
        - namespace
        - gitops_namespace
        - application_id
        - owner
      properties:
        cluster_id:
          title: Cluster Id
          type: string
          description: Id of the cluster
          default: .apps.demo-01-rhsys.wzhlab.top
        namespace: 
          title: Namespace
          type: string
          description: Namespace
          default: demo-play
        gitops_namespace:
          title: GitOps Namespace
          type: string
          description: Namespace for storing gitops resources
          default: janus-argocd
        application_id: 
          title: Application Id
          type: string
          description: Id of the application
          default: demo-02
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind: [User]
    - title: Provide Build Information
      required:
        - image_host
        - image_tag
      properties:
        image_host:
          title: Image Host
          type: string
          description: Host for storing image (defaults to openshift internal)
          default: image-registry.openshift-image-registry.svc:5000
        image_tag:
          title: Image Tag
          default: latest
          type: string
          description: Image tag to use for storing in the internal registry
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          git_host: ${{ parameters.git_host }}
          gitlabGroup: ${{ parameters.githubOrg }}
          repoName: ${{parameters.namespace}}-${{parameters.application_id}}
          owner: ${{parameters.owner}}
          cluster_id: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.namespace}}-${{parameters.application_id}}
          application_id: ${{parameters.application_id}}
          description: ${{parameters.description}}
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:github
      input:
        sourcePath: ./source
        description: ${{parameters.description}}
        repoUrl: ${{ parameters.git_host }}?owner=${{ parameters.githubOrg }}&repo=${{parameters.namespace}}-${{parameters.application_id}}
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          git_host: ${{ parameters.git_host }}
          component_id: ${{parameters.namespace}}-${{parameters.application_id}}
          description: ${{parameters.description}}
          destination: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-${{parameters.application_id}}-gitops.git
          source_repository: https://github.com/${{parameters.githubOrg}}/${{parameters.namespace}}-${{parameters.application_id}}.git
          repository_name: ${{parameters.namespace}}-${{parameters.application_id}}
          git_owner: ${{parameters.githubOrg}}
          # git_token: ${{parameters.git_token}}
          cluster: ${{parameters.cluster_id}}
          namespace: ${{parameters.namespace}}
          gitops_namespace: ${{parameters.gitops_namespace}}
          image_host: ${{parameters.image_host}}
          image_name: ${{parameters.namespace}}/${{parameters.application_id}}
          image_tag: ${{parameters.image_tag}}
          application_id: ${{parameters.application_id}}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=${{parameters.githubOrg}}&repo=${{parameters.namespace}}-${{parameters.application_id}}-gitops
        title: gitops resources for ${{parameters.namespace}}-${{parameters.application_id}}
        description: gitops resources for ${{parameters.namespace}}-${{parameters.application_id}}
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: registerSource1
      name: Register Quarkus Service Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml
    - id: registerSource2
      name: Register Angular Frontend Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /src/main/angular/catalog-info.yaml
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.namespace}}-${{parameters.application_id}}-bootstrap
        argoInstance: main
        namespace: ${{parameters.gitops_namespace}}
        repoUrl: https://${{ parameters.git_host }}/${{parameters.githubOrg}}/${{parameters.namespace}}-${{parameters.application_id}}-gitops.git
        path: 'argocd/'
  output:
    links:
      - title: Source Code Repository
        url: https://${{ parameters.git_host }}/${{parameters.githubOrg}}/${{parameters.namespace}}-${{parameters.application_id}}
      - title: Pipeline status
        url: https://console-openshift-console${{parameters.cluster_id}}/dev-pipelines/ns/${{parameters.namespace}}/
      - title: Open Quarkus Service Component
        icon: catalog
        entityRef: ${{steps.registerSource1.output.entityRef}}
      - title: Open Angular Frontend Component
        icon: catalog
        entityRef: ${{steps.registerSource2.output.entityRef}}
